# Generated by Django 4.1.3 on 2022-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='buyer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
