# Generated by Django 4.1.3 on 2022-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cows', '0003_sorting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sorting',
        ),
        migrations.AddField(
            model_name='cow',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
