# Generated by Django 4.1.3 on 2023-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cows', '0004_delete_sorting_cow_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='buyer',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
