# Generated by Django 4.1.3 on 2023-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cows', '0005_alter_cow_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='buyer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
