# Generated by Django 4.1.3 on 2022-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_krow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='krowa',
            name='earring_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
