# Generated by Django 4.1.3 on 2023-01-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earring_number', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Owca', 'Owca'), ('Baran', 'Baran')], max_length=5)),
                ('buyer', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('calving_date', models.DateField(blank=True, null=True)),
                ('estrus_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
