# Generated by Django 4.1.3 on 2023-01-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.CharField(max_length=10, unique=True)),
                ('ar_label', models.CharField(max_length=10, unique=True)),
                ('mr_label', models.CharField(max_length=10, unique=True)),
                ('area', models.FloatField()),
                ('location', models.CharField(choices=[('Kobylno', 'Kobylno'), ('Bierdzany', 'Bierdzany'), ('Kopalina', 'Kopalina'), ('Inna', 'Inna')], max_length=15)),
                ('field_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('soil_richness', models.FloatField(blank=True, null=True)),
                ('acidity', models.FloatField(blank=True, null=True)),
                ('last_seed', models.CharField(max_length=10, null=True)),
                ('present_seed', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spraying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.field')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('hight', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.field')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.field')),
            ],
        ),
    ]
