# Generated by Django 4.1.3 on 2023-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='mr_label',
        ),
    ]
