# Generated by Django 4.1.3 on 2023-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0002_remove_field_mr_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='last_seed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
