# Generated by Django 4.1.3 on 2023-01-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0003_alter_field_field_image_alter_field_last_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPK_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen_product', models.FloatField(blank=True, null=True)),
                ('phosphorus_product', models.FloatField(blank=True, null=True)),
                ('potassium_product', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPK_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('nitrogen_field', models.FloatField(blank=True, null=True)),
                ('phosphorus_field', models.FloatField(blank=True, null=True)),
                ('potassium_field', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.field')),
            ],
        ),
    ]
