# Generated by Django 4.1.3 on 2023-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0004_npk_product_npk_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='npk_product',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='npk_product',
            name='product_firm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='npk_product',
            name='product_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
